// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBvH7awX_vNXKMLEaahubLIP_v7eX8gmA',
    appId: '1:48599307723:android:b2fe072b8ead1ac7e8924e',
    messagingSenderId: '48599307723',
    projectId: 'flutter-firebase-notific-2d1e0',
    storageBucket: 'flutter-firebase-notific-2d1e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiIHFS2z6IlsM3W2YaR01wcSgpG69wS44',
    appId: '1:48599307723:ios:288f8a7c5e770f60e8924e',
    messagingSenderId: '48599307723',
    projectId: 'flutter-firebase-notific-2d1e0',
    storageBucket: 'flutter-firebase-notific-2d1e0.firebasestorage.app',
    iosClientId: '48599307723-v40t45hcaqk845cmkfimrt4bqk4rdpis.apps.googleusercontent.com',
    iosBundleId: 'com.example.streamlyCresolinfoserv',
  );
}
